Repository GoogleCloudPlatform/spring-cloud-gcp, pull requests merged in 2021-02, with the labels that each got.

#250 Allow rollback of aborted transactions
  spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerTransactionManager.java
Labels: spanner

#260 Reference documentation improvements
  .github/workflows/updateDocs.yaml
  docs/src/main/asciidoc/spring-cloud-gcp.adoc
Labels: documentation

#277 Handle NPE with getPersistentEntity in Datastore
  spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/datastore/DatastoreKeyIdConverter.java
  spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplate.java
  spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/convert/DefaultDatastoreEntityConverter.java
  spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/mapping/DatastoreMappingContext.java
  spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/mapping/DatastorePersistentEntityImpl.java
  spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/query/PartTreeDatastoreQuery.java
  spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/mapping/DatastoreMappingContextTests.java
Labels: code-quality, datastore

#279 Fix parameterized type code smells in Datastore
  spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplate.java
Labels: code-quality, datastore

#293 Fix SC: 'NPE could be throw here' for Firestore/Firebase classes
  spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java
  spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/mapping/FirestorePersistentEntityImpl.java
  spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java
  spring-cloud-gcp-security-firebase/src/main/java/com/google/cloud/spring/security/firebase/FirebaseJwtTokenDecoder.java
  spring-cloud-gcp-security-firebase/src/test/java/com/google/cloud/spring/security/firebase/FirebaseJwtTokenDecoderTests.java
Labels: code-quality

#294 Missed this generic class name in #289
  spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/support/SimpleSpannerRepository.java
Labels: code-quality

#308 Fix last 2 'NPE could be thrown here' bugs
  spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/datastore/DatastoreKeyIdConverter.java
Labels: code-quality

#312 Break up monster Datstore integration test
  spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java
  spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/TransactionalTemplateService.java
Labels: code-quality, testing

#313 Reduce usage of deprecated classes
  spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/logging/StackdriverLoggingAutoConfiguration.java
  spring-cloud-gcp-cloudfoundry/src/main/java/com/google/cloud/spring/cloudfoundry/GcpCloudFoundryEnvironmentPostProcessor.java
  spring-cloud-gcp-core/src/main/java/com/google/cloud/spring/core/DefaultCredentialsProvider.java
  spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/convert/DefaultDatastoreEntityConverter.java
  spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/mapping/FirestorePersistentEntityImpl.java
  spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityReader.java
  spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/StackdriverJsonLayout.java
  spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/publisher/PubSubPublisherTemplate.java
  src/checkstyle/checkstyle-suppressions.xml
Labels: code-quality

#319 Few more
  spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepository.java
  spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/support/ReactiveFirestoreRepositoryFactory.java
  spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerQueryLookupStrategy.java
Labels: code-quality

#262 Allow specifying a custom subscription as a consumer endpoint
  docs/src/main/asciidoc/spring-stream.adoc
  spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/properties/PubSubConsumerProperties.java
  spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java
  spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java
  spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/resources/application.properties
Labels: pubsub

#336 Add lazy `@Interleaved` example to Spanner sample
  spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/SpannerRepositoryExample.java
  spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/Trader.java
  spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/test/java/com/example/SpannerRepositoryIntegrationTests.java
Labels: spanner

#340 Set up unified maven cache for GH Actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/integrationTests.yaml
  .github/workflows/linkageCheck.yaml
  .github/workflows/sonar.yaml
  .github/workflows/unitTests.yaml
  .github/workflows/updateDocs.yaml
Labels: build
