Repository GoogleCloudPlatform/spring-cloud-gcp, pull requests merged in 2023-07, with the labels that each got.

#1999 chore: fix spring-cloud-generator scripts after refactor
  spring-cloud-generator/scripts/generate-library-list.sh
  spring-cloud-generator/scripts/generate-steps.sh
Labels: codegen

#1957 test: setup showcase testing for codegen modules
  .github/workflows/showcaseTests.yaml
  spring-cloud-generator/README.md
  spring-cloud-generator/scripts/generate-showcase.sh
  spring-cloud-generator/scripts/generate-steps.sh
  spring-cloud-generator/scripts/generate.sh
  spring-cloud-generator/showcase/showcase-spring-starter/pom.xml
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/ComplianceSpringAutoConfiguration.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/ComplianceSpringProperties.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/EchoSpringAutoConfiguration.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/EchoSpringProperties.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/IdentitySpringAutoConfiguration.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/IdentitySpringProperties.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/MessagingSpringAutoConfiguration.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/MessagingSpringProperties.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/SequenceServiceSpringAutoConfiguration.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/SequenceServiceSpringProperties.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/TestingSpringAutoConfiguration.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/TestingSpringProperties.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/package-info.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  spring-cloud-generator/showcase/showcase-spring-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-cloud-generator/showcase/showcase-spring-starter/src/test/java/com/google/showcase/v1beta1/spring/EchoAutoConfigurationTests.java
  spring-cloud-generator/showcase/showcase-spring-starter/src/test/resources/fake-credential-key-2.json
  spring-cloud-generator/showcase/showcase-spring-starter/src/test/resources/fake-credential-key.json
Labels: codegen

#2012 fix: timestampNanos field with nanos precision.
  spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/StackdriverJsonLayout.java
  spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/StackdriverJsonLayoutLoggerTests.java
Labels: pubsub

#1971 feat: Migrate spanner spring data r2dbc
  docs/src/main/asciidoc/index.adoc
  docs/src/main/asciidoc/spanner-spring-data-r2dbc.adoc
  pom.xml
  spring-cloud-gcp-dependencies/pom.xml
  spring-cloud-gcp-samples/pom.xml
  spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/README.adoc
  spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/pom.xml
  spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/java/com/example/Book.java
  spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/java/com/example/BookRepository.java
  spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/java/com/example/CustomConfiguration.java
  spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/java/com/example/Review.java
  spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/java/com/example/SpringDataR2dbcApp.java
  spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/java/com/example/WebController.java
  spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/resources/application.properties
  spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/resources/static/index.html
  spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/test/java/com/example/SpringDataR2dbcAppIntegrationTest.java
  spring-cloud-spanner-spring-data-r2dbc/pom.xml
  spring-cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/JsonToMapConverter.java
  spring-cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/MapToJsonConverter.java
  spring-cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerArrayColumns.java
  spring-cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerBindMarkerFactoryProvider.java
  spring-cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialect.java
  spring-cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialectProvider.java
  spring-cloud-spanner-spring-data-r2dbc/src/main/resources/META-INF/spring.factories
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/MapJsonConverterTest.java
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/SpannerArrayColumnsTest.java
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/SpannerBindMarkerFactoryProviderTest.java
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialectTest.java
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/SpannerR2dbcDialectDateTimeBindingIntegrationTest.java
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/SpannerR2dbcDialectIntegrationTest.java
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/SpannerR2dbcDialectJsonIntegrationTest.java
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/SpannerTestUtils.java
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/entities/Address.java
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/entities/Card.java
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/entities/Person.java
  spring-cloud-spanner-spring-data-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/springdata/it/entities/President.java
Labels: cla:yes, do not merge
